In [1]:
#import libraries
from urllib.request import urlretrieve
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
import numpy as np
import seaborn as sns
import os


In [2]:
#collect the 2020 Season Data
url = 'https://oracleselixir-downloadable-match-data.s3-us-west-2.amazonaws.com/2020_LoL_esports_match_data_from_OraclesElixir_20200821.csv'

fullfilename = os.path.join('/Users/dankang/Desktop/SpringBoard/Capstone2/Capstone2/data/external', '2020-LoL-matches.csv')
urlretrieve(url, fullfilename)


('/Users/dankang/Desktop/SpringBoard/Capstone2/Capstone2/data/external/2020-LoL-matches.csv',
 <http.client.HTTPMessage at 0x7f9441c7e650>)

In [3]:
#save to a dataframe
game_data = pd.read_csv(fullfilename)


In [4]:
#lets take a look at the data
game_data.info()
game_data.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62616 entries, 0 to 62615
Columns: 103 entries, gameid to csdiffat15
dtypes: float64(67), int64(20), object(16)
memory usage: 49.2+ MB


gameid               object
datacompleteness     object
url                  object
league               object
year                  int64
                     ...   
opp_xpat15          float64
opp_csat15          float64
golddiffat15        float64
xpdiffat15          float64
csdiffat15          float64
Length: 103, dtype: object

From here we can see there are 62,616 entries, and 103 columns / features

In [5]:
#check for null values
game_data.isnull().values.any()

True

There are null entries, but rather than address them now we will address them a bit later

In [6]:
#lets isolate the number of league entries
game_data.league.unique()

array(['KeSPA', 'LPL', 'LFL', 'LEC', 'LCS.A', 'CBLOL', 'LCS', 'OPL',
       'VCS', 'TCL', 'TRA', 'BRCC', 'LCK', 'CK', 'LJL', 'LLA', 'LCL',
       'PCS', 'EM', 'LDL', 'OCS', 'Riot', 'MSC'], dtype=object)

We want to eventually isolate the LCS. We note that the LCS.A is the Academy/minor league, so we ignore that entry later on



In [7]:
#make sure year is datetime object
game_data['year'] = pd.to_datetime(game_data['year'])
game_data.dtypes

gameid                      object
datacompleteness            object
url                         object
league                      object
year                datetime64[ns]
                         ...      
opp_xpat15                 float64
opp_csat15                 float64
golddiffat15               float64
xpdiffat15                 float64
csdiffat15                 float64
Length: 103, dtype: object

In [8]:
#do the same for playerid, game, and playoffs: make sure they are categories
game_data['playerid'] = game_data['playerid'].astype('category')
game_data['game'] = game_data['game'].astype('category')
game_data['playoffs'] = game_data['playoffs'].astype('category')

In [9]:
#lets take a look at the first ten entries of our dataframe
game_data.head(10)

gameid datacompleteness  \
0  ESPORTSTMNT03/1241318         complete   
1  ESPORTSTMNT03/1241318         complete   
2  ESPORTSTMNT03/1241318         complete   
3  ESPORTSTMNT03/1241318         complete   
4  ESPORTSTMNT03/1241318         complete   
5  ESPORTSTMNT03/1241318         complete   
6  ESPORTSTMNT03/1241318         complete   
7  ESPORTSTMNT03/1241318         complete   
8  ESPORTSTMNT03/1241318         complete   
9  ESPORTSTMNT03/1241318         complete   

                                                 url league  \
0  http://matchhistory.na.leagueoflegends.com/en/...  KeSPA   
1  http://matchhistory.na.leagueoflegends.com/en/...  KeSPA   
2  http://matchhistory.na.leagueoflegends.com/en/...  KeSPA   
3  http://matchhistory.na.leagueoflegends.com/en/...  KeSPA   
4  http://matchhistory.na.leagueoflegends.com/en/...  KeSPA   
5  http://matchhistory.na.leagueoflegends.com/en/...  KeSPA   
6  http://matchhistory.na.leagueoflegends.com/en/...  KeSPA   
7  http://matchhistory.na.leagueoflegends.com/en/...  KeSPA   
8  http://matchhistory.na.leagueoflegends.com/en/...  KeSPA   
9  http://matchhistory.na.leagueoflegends.com/en/...  KeSPA   

                           year split playoffs                 date game  \
0 1970-01-01 00:00:00.000002020   NaN        0  2020-01-03 07:33:26    1   
1 1970-01-01 00:00:00.000002020   NaN        0  2020-01-03 07:33:26    1   
2 1970-01-01 00:00:00.000002020   NaN        0  2020-01-03 07:33:26    1   
3 1970-01-01 00:00:00.000002020   NaN        0  2020-01-03 07:33:26    1   
4 1970-01-01 00:00:00.000002020   NaN        0  2020-01-03 07:33:26    1   
5 1970-01-01 00:00:00.000002020   NaN        0  2020-01-03 07:33:26    1   
6 1970-01-01 00:00:00.000002020   NaN        0  2020-01-03 07:33:26    1   
7 1970-01-01 00:00:00.000002020   NaN        0  2020-01-03 07:33:26    1   
8 1970-01-01 00:00:00.000002020   NaN        0  2020-01-03 07:33:26    1   
9 1970-01-01 00:00:00.000002020   NaN        0  2020-01-03 07:33:26    1   

   patch  ... csdiffat10 goldat15  xpat15 csat15 opp_goldat15 opp_xpat15  \
0   9.24  ...       23.0   4888.0  7368.0  131.0       4723.0     7202.0   
1   9.24  ...      -10.0   4385.0  4817.0   91.0       4784.0     4667.0   
2   9.24  ...       -9.0   4809.0  6275.0  129.0       5218.0     8112.0   
3   9.24  ...        3.0   4915.0  4959.0  136.0       4864.0     5360.0   
4   9.24  ...        1.0   2956.0  3800.0   20.0       3189.0     3543.0   
5   9.24  ...      -23.0   4723.0  7202.0  118.0       4888.0     7368.0   
6   9.24  ...       10.0   4784.0  4667.0   98.0       4385.0     4817.0   
7   9.24  ...        9.0   5218.0  8112.0  140.0       4809.0     6275.0   
8   9.24  ...       -3.0   4864.0  5360.0  135.0       4915.0     4959.0   
9   9.24  ...       -1.0   3189.0  3543.0   28.0       2956.0     3800.0   

  opp_csat15 golddiffat15 xpdiffat15 csdiffat15  
0      118.0        165.0      166.0       13.0  
1       98.0       -399.0      150.0       -7.0  
2      140.0       -409.0    -1837.0      -11.0  
3      135.0         51.0     -401.0        1.0  
4       28.0       -233.0      257.0       -8.0  
5      131.0       -165.0     -166.0      -13.0  
6       91.0        399.0     -150.0        7.0  
7      129.0        409.0     1837.0       11.0  
8      136.0        -51.0      401.0       -1.0  
9       20.0        233.0     -257.0        8.0  

[10 rows x 103 columns]

There are more than two entries per game, despite there only being 2 teams. This is because our dataframe currently aggregates match statistics for individual players -- we care only about the team. In this notebook we will isolate the team entries.

In [10]:
game_data[game_data.gameid == 'ESPORTSTMNT03/1241318'].T

0   \
gameid                                        ESPORTSTMNT03/1241318   
datacompleteness                                           complete   
url               http://matchhistory.na.leagueoflegends.com/en/...   
league                                                        KeSPA   
year                                  1970-01-01 00:00:00.000002020   
...                                                             ...   
opp_xpat15                                                     7202   
opp_csat15                                                      118   
golddiffat15                                                    165   
xpdiffat15                                                      166   
csdiffat15                                                       13   

                                                                 1   \
gameid                                        ESPORTSTMNT03/1241318   
datacompleteness                                           complete   
url               http://matchhistory.na.leagueoflegends.com/en/...   
league                                                        KeSPA   
year                                  1970-01-01 00:00:00.000002020   
...                                                             ...   
opp_xpat15                                                     4667   
opp_csat15                                                       98   
golddiffat15                                                   -399   
xpdiffat15                                                      150   
csdiffat15                                                       -7   

                                                                 2   \
gameid                                        ESPORTSTMNT03/1241318   
datacompleteness                                           complete   
url               http://matchhistory.na.leagueoflegends.com/en/...   
league                                                        KeSPA   
year                                  1970-01-01 00:00:00.000002020   
...                                                             ...   
opp_xpat15                                                     8112   
opp_csat15                                                      140   
golddiffat15                                                   -409   
xpdiffat15                                                    -1837   
csdiffat15                                                      -11   

                                                                 3   \
gameid                                        ESPORTSTMNT03/1241318   
datacompleteness                                           complete   
url               http://matchhistory.na.leagueoflegends.com/en/...   
league                                                        KeSPA   
year                                  1970-01-01 00:00:00.000002020   
...                                                             ...   
opp_xpat15                                                     5360   
opp_csat15                                                      135   
golddiffat15                                                     51   
xpdiffat15                                                     -401   
csdiffat15                                                        1   

                                                                 4   \
gameid                                        ESPORTSTMNT03/1241318   
datacompleteness                                           complete   
url               http://matchhistory.na.leagueoflegends.com/en/...   
league                                                        KeSPA   
year                                  1970-01-01 00:00:00.000002020   
...                                                             ...   
opp_xpat15                                                     3543   
opp_csat15                                                       28   
golddiffat15  

In fact, there are 12 entries for the first game listed: 5 team members, one team entry (and 2 teams. Let's explore the datatypes of the columns

In [11]:
game_data.select_dtypes(include='object')

gameid datacompleteness  \
0      ESPORTSTMNT03/1241318         complete   
1      ESPORTSTMNT03/1241318         complete   
2      ESPORTSTMNT03/1241318         complete   
3      ESPORTSTMNT03/1241318         complete   
4      ESPORTSTMNT03/1241318         complete   
...                      ...              ...   
62611  ESPORTSTMNT03/1441781         complete   
62612  ESPORTSTMNT03/1441781         complete   
62613  ESPORTSTMNT03/1441781         complete   
62614  ESPORTSTMNT03/1441781         complete   
62615  ESPORTSTMNT03/1441781         complete   

                                                     url league    split  \
0      http://matchhistory.na.leagueoflegends.com/en/...  KeSPA      NaN   
1      http://matchhistory.na.leagueoflegends.com/en/...  KeSPA      NaN   
2      http://matchhistory.na.leagueoflegends.com/en/...  KeSPA      NaN   
3      http://matchhistory.na.leagueoflegends.com/en/...  KeSPA      NaN   
4      http://matchhistory.na.leagueoflegends.com/en/...  KeSPA      NaN   
...                                                  ...    ...      ...   
62611  http://matchhistory.na.leagueoflegends.com/en/...    OPL  Split 2   
62612  http://matchhistory.na.leagueoflegends.com/en/...    OPL  Split 2   
62613  http://matchhistory.na.leagueoflegends.com/en/...    OPL  Split 2   
62614  http://matchhistory.na.leagueoflegends.com/en/...    OPL  Split 2   
62615  http://matchhistory.na.leagueoflegends.com/en/...    OPL  Split 2   

                      date  side position    player                 team  \
0      2020-01-03 07:33:26  Blue      top    Summit       SANDBOX Gaming   
1      2020-01-03 07:33:26  Blue      jng   OnFleek       SANDBOX Gaming   
2      2020-01-03 07:33:26  Blue      mid      FATE       SANDBOX Gaming   
3      2020-01-03 07:33:26  Blue      bot       Leo       SANDBOX Gaming   
4      2020-01-03 07:33:26  Blue      sup   GorillA       SANDBOX Gaming   
...                    ...   ...      ...       ...                  ...   
62611  2020-08-21 06:41:59   Red      mid    Claire  Chiefs Esports Club   
62612  2020-08-21 06:41:59   Red      bot  Katsurii  Chiefs Esports Club   
62613  2020-08-21 06:41:59   Red      sup    Dragku  Chiefs Esports Club   
62614  2020-08-21 06:41:59  Blue     team       NaN          Pentanet.GG   
62615  2020-08-21 06:41:59   Red     team       NaN  Chiefs Esports Club   

           champion     ban1     ban2     ban3       ban4      ban5  
0            Rumble  LeBlanc   Irelia  Rek'Sai      Yasuo  Renekton  
1             Elise  LeBlanc   Irelia  Rek'Sai      Yasuo  Renekton  
2            Qiyana  LeBlanc   Irelia  Rek'Sai      Yasuo  Renekton  
3      Miss Fortune  LeBlanc   Irelia  Rek'Sai      Yasuo  Renekton  
4          Nautilus  LeBlanc   Irelia  Rek'Sai      Yasuo  Renekton  
...             ...      ...      ...      ...        ...       ...  
62611         Akali   Thresh  Caitlyn    Karma       Lulu   Morgana  
62612          Ashe   Thresh  Caitlyn    Karma       Lulu   Morgana  
62613          Sett   Thresh  Caitlyn    Karma       Lulu   Morgana  
62614           NaN  Nidalee     Olaf    Yuumi  Gangplank     Jayce  
62615           NaN   Thresh  Caitlyn    Karma       Lulu   Morgana  

[62616 rows x 16 columns]

Lets now make sure that we add Match identifiers for each game, so we can not only record game wins but also record match wins. We also need to add in match wins in a new results column.

In [12]:
game_data.insert(0, 'matchid', 0)
game_data.head()

matchid                 gameid datacompleteness  \
0        0  ESPORTSTMNT03/1241318         complete   
1        0  ESPORTSTMNT03/1241318         complete   
2        0  ESPORTSTMNT03/1241318         complete   
3        0  ESPORTSTMNT03/1241318         complete   
4        0  ESPORTSTMNT03/1241318         complete   

                                                 url league  \
0  http://matchhistory.na.leagueoflegends.com/en/...  KeSPA   
1  http://matchhistory.na.leagueoflegends.com/en/...  KeSPA   
2  http://matchhistory.na.leagueoflegends.com/en/...  KeSPA   
3  http://matchhistory.na.leagueoflegends.com/en/...  KeSPA   
4  http://matchhistory.na.leagueoflegends.com/en/...  KeSPA   

                           year split playoffs                 date game  ...  \
0 1970-01-01 00:00:00.000002020   NaN        0  2020-01-03 07:33:26    1  ...   
1 1970-01-01 00:00:00.000002020   NaN        0  2020-01-03 07:33:26    1  ...   
2 1970-01-01 00:00:00.000002020   NaN        0  2020-01-03 07:33:26    1  ...   
3 1970-01-01 00:00:00.000002020   NaN        0  2020-01-03 07:33:26    1  ...   
4 1970-01-01 00:00:00.000002020   NaN        0  2020-01-03 07:33:26    1  ...   

   csdiffat10 goldat15  xpat15 csat15 opp_goldat15 opp_xpat15 opp_csat15  \
0        23.0   4888.0  7368.0  131.0       4723.0     7202.0      118.0   
1       -10.0   4385.0  4817.0   91.0       4784.0     4667.0       98.0   
2        -9.0   4809.0  6275.0  129.0       5218.0     8112.0      140.0   
3         3.0   4915.0  4959.0  136.0       4864.0     5360.0      135.0   
4         1.0   2956.0  3800.0   20.0       3189.0     3543.0       28.0   

  golddiffat15 xpdiffat15 csdiffat15  
0        165.0      166.0       13.0  
1       -399.0      150.0       -7.0  
2       -409.0    -1837.0      -11.0  
3         51.0     -401.0        1.0  
4       -233.0      257.0       -8.0  

[5 rows x 104 columns]

In [13]:
#set the first match id
game_data.iloc[0, game_data.columns.get_loc('matchid')] = 1

In [14]:
game_data.head()

matchid                 gameid datacompleteness  \
0        1  ESPORTSTMNT03/1241318         complete   
1        0  ESPORTSTMNT03/1241318         complete   
2        0  ESPORTSTMNT03/1241318         complete   
3        0  ESPORTSTMNT03/1241318         complete   
4        0  ESPORTSTMNT03/1241318         complete   

                                                 url league  \
0  http://matchhistory.na.leagueoflegends.com/en/...  KeSPA   
1  http://matchhistory.na.leagueoflegends.com/en/...  KeSPA   
2  http://matchhistory.na.leagueoflegends.com/en/...  KeSPA   
3  http://matchhistory.na.leagueoflegends.com/en/...  KeSPA   
4  http://matchhistory.na.leagueoflegends.com/en/...  KeSPA   

                           year split playoffs                 date game  ...  \
0 1970-01-01 00:00:00.000002020   NaN        0  2020-01-03 07:33:26    1  ...   
1 1970-01-01 00:00:00.000002020   NaN        0  2020-01-03 07:33:26    1  ...   
2 1970-01-01 00:00:00.000002020   NaN        0  2020-01-03 07:33:26    1  ...   
3 1970-01-01 00:00:00.000002020   NaN        0  2020-01-03 07:33:26    1  ...   
4 1970-01-01 00:00:00.000002020   NaN        0  2020-01-03 07:33:26    1  ...   

   csdiffat10 goldat15  xpat15 csat15 opp_goldat15 opp_xpat15 opp_csat15  \
0        23.0   4888.0  7368.0  131.0       4723.0     7202.0      118.0   
1       -10.0   4385.0  4817.0   91.0       4784.0     4667.0       98.0   
2        -9.0   4809.0  6275.0  129.0       5218.0     8112.0      140.0   
3         3.0   4915.0  4959.0  136.0       4864.0     5360.0      135.0   
4         1.0   2956.0  3800.0   20.0       3189.0     3543.0       28.0   

  golddiffat15 xpdiffat15 csdiffat15  
0        165.0      166.0       13.0  
1       -399.0      150.0       -7.0  
2       -409.0    -1837.0      -11.0  
3         51.0     -401.0        1.0  
4       -233.0      257.0       -8.0  

[5 rows x 104 columns]

In [15]:
#set the matchids
for i in range(1, len(game_data.index)):
    if game_data.iloc[i, game_data.columns.get_loc('game')] >= game_data.iloc[i-1, game_data.columns.get_loc('game')]:
         game_data.iloc[i, game_data.columns.get_loc('matchid')] = game_data.iloc[i-1, game_data.columns.get_loc('matchid')]
    else:
        game_data.iloc[i, game_data.columns.get_loc('matchid')] = game_data.iloc[i-1, game_data.columns.get_loc('matchid')] + 1

In [16]:
game_data.head()
game_data.tail()

matchid                 gameid datacompleteness  \
62611     1249  ESPORTSTMNT03/1441781         complete   
62612     1249  ESPORTSTMNT03/1441781         complete   
62613     1249  ESPORTSTMNT03/1441781         complete   
62614     1249  ESPORTSTMNT03/1441781         complete   
62615     1249  ESPORTSTMNT03/1441781         complete   

                                                     url league  \
62611  http://matchhistory.na.leagueoflegends.com/en/...    OPL   
62612  http://matchhistory.na.leagueoflegends.com/en/...    OPL   
62613  http://matchhistory.na.leagueoflegends.com/en/...    OPL   
62614  http://matchhistory.na.leagueoflegends.com/en/...    OPL   
62615  http://matchhistory.na.leagueoflegends.com/en/...    OPL   

                               year    split playoffs                 date  \
62611 1970-01-01 00:00:00.000002020  Split 2        1  2020-08-21 06:41:59   
62612 1970-01-01 00:00:00.000002020  Split 2        1  2020-08-21 06:41:59   
62613 1970-01-01 00:00:00.000002020  Split 2        1  2020-08-21 06:41:59   
62614 1970-01-01 00:00:00.000002020  Split 2        1  2020-08-21 06:41:59   
62615 1970-01-01 00:00:00.000002020  Split 2        1  2020-08-21 06:41:59   

      game  ...  csdiffat10 goldat15   xpat15 csat15 opp_goldat15 opp_xpat15  \
62611    2  ...        -6.0   4563.0   6651.0  124.0       5503.0     7504.0   
62612    2  ...        -1.0   5652.0   4968.0  133.0       5185.0     4844.0   
62613    2  ...        -1.0   3464.0   4320.0   22.0       3081.0     3912.0   
62614    2  ...       -12.0  23296.0  27933.0  479.0      23742.0    28828.0   
62615    2  ...        12.0  23742.0  28828.0  500.0      23296.0    27933.0   

      opp_csat15 golddiffat15 xpdiffat15 csdiffat15  
62611      140.0       -940.0     -853.0      -16.0  
62612      134.0        467.0      124.0       -1.0  
62613       21.0        383.0      408.0        1.0  
62614      500.0       -446.0     -895.0      -21.0  
62615      479.0        446.0      895.0       21.0  

[5 rows x 104 columns]

In [17]:
match_count = game_data['matchid'].unique()
print(match_count)
print(match_count[0])

[   1    2    3 ... 1247 1248 1249]
1


In [18]:
game_data.insert(23, 'match_result', 0)

Below we breakdown the logic for recording MATCH wins, for the first match (then we iterate through the whole dataframe)

In [19]:
first_match = game_data[game_data['matchid'] == 1]

In [20]:
first_match.head()
first_match.index

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
           dtype='int64')

In [21]:
teams = first_match['team'].unique()
print(teams)

['SANDBOX Gaming' 'T1']


In [22]:
team1 = teams[0]
team2 = teams[1]

sum1 = first_match.loc[first_match['team'] == team1, 'result'].sum()
sum2 = first_match.loc[first_match['team'] == team2, 'result'].sum()

print(sum1)
print(sum2)


if sum1 > sum2:
    for i in range(len(first_match.index)):
        if first_match.iloc[i, first_match.columns.get_loc('team')] == team1:
            first_match.iloc[i, first_match.columns.get_loc('match_result')] = 1
        else:
            first_match.iloc[i, first_match.columns.get_loc('match_result')] = 0
else:
    for i in range(len(first_match.index)):
        if first_match.iloc[i, first_match.columns.get_loc('team')] == team1:
            first_match.iloc[i, first_match.columns.get_loc('match_result')] = 0
        else:
            first_match.iloc[i, first_match.columns.get_loc('match_result')] = 1


            

18
6


/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)


In [23]:
print(first_match.match_result)
print(first_match[first_match['team'] == team1].match_result)

0     1
1     1
2     1
3     1
4     1
5     0
6     0
7     0
8     0
9     0
10    1
11    0
12    0
13    0
14    0
15    0
16    0
17    1
18    1
19    1
20    1
21    1
22    0
23    1
24    0
25    0
26    0
27    0
28    0
29    1
30    1
31    1
32    1
33    1
34    0
35    1
36    0
37    0
38    0
39    0
40    0
41    1
42    1
43    1
44    1
45    1
46    0
47    1
Name: match_result, dtype: int64
0     1
1     1
2     1
3     1
4     1
10    1
17    1
18    1
19    1
20    1
21    1
23    1
29    1
30    1
31    1
32    1
33    1
35    1
41    1
42    1
43    1
44    1
45    1
47    1
Name: match_result, dtype: int64


In [24]:
game_data.loc[first_match.index,first_match.columns] = first_match
print(game_data.match_result)

0        1
1        1
2        1
3        1
4        1
        ..
62611    0
62612    0
62613    0
62614    0
62615    0
Name: match_result, Length: 62616, dtype: int64


Lets reflect these changes in the game_data dataframe now

Now lets record match results for the entire dataframe, following the steps taken above

In [25]:
for i in match_count:
    match = game_data[game_data['matchid'] == i]
    teams = first_match['team'].unique()
    team1 = teams[0]
    team2 = teams[1]
    
    sum1 = match.loc[match['team'] == team1, 'result'].sum()
    sum2 = match.loc[match['team'] == team2, 'result'].sum()

    if sum1 > sum2:
        for k in range(len(match.index)):
            if match.iloc[k, match.columns.get_loc('team')] == team1:
                match.iloc[k, match.columns.get_loc('match_result')] = 1
            else:
                match.iloc[k, match.columns.get_loc('match_result')] = 0
    else:
        for k in range(len(match.index)):
            if match.iloc[k, match.columns.get_loc('team')] == team1:
                match.iloc[k, match.columns.get_loc('match_result')] = 0
            else:
                match.iloc[k, match.columns.get_loc('match_result')] = 1
    game_data.loc[match.index,match.columns] = match
                


/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/dankang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,

In [58]:
game_data['match_result'].unique()
game_data['match_result'].value_counts()


1    60276
0     2340
Name: match_result, dtype: int64

In [27]:
game_data[game_data.gameid == 'ESPORTSTMNT03/1241318'].T.head(26)

0   \
matchid                                                           1   
gameid                                        ESPORTSTMNT03/1241318   
datacompleteness                                           complete   
url               http://matchhistory.na.leagueoflegends.com/en/...   
league                                                        KeSPA   
year                                  1970-01-01 00:00:00.000002020   
split                                                           NaN   
playoffs                                                          0   
date                                            2020-01-03 07:33:26   
game                                                              1   
patch                                                          9.24   
playerid                                                          1   
side                                                           Blue   
position                                                        top   
player                                                       Summit   
team                                                 SANDBOX Gaming   
champion                                                     Rumble   
ban1                                                        LeBlanc   
ban2                                                         Irelia   
ban3                                                        Rek'Sai   
ban4                                                          Yasuo   
ban5                                                       Renekton   
gamelength                                                     2220   
match_result                                                      1   
result                                                            1   
kills                                                             0   

                                                                 1   \
matchid                                                           1   
gameid                                        ESPORTSTMNT03/1241318   
datacompleteness                                           complete   
url               http://matchhistory.na.leagueoflegends.com/en/...   
league                                                        KeSPA   
year                                  1970-01-01 00:00:00.000002020   
split                                                           NaN   
playoffs                                                          0   
date                                            2020-01-03 07:33:26   
game                                                              1   
patch                                                          9.24   
playerid                                                          2   
side                                                           Blue   
position                                                        jng   
player                                                      OnFleek   
team                                                 SANDBOX Gaming   
champion                                                      Elise   
ban1                                                        LeBlanc   
ban2                                                         Irelia   
ban3                                                        Rek'Sai   
ban4                                                          Yasuo   
ban5                                                       Renekton   
gamelength                                                     2220   
match_result                                                      1   
result                                                            1   
kills                                                             4   

                                                                 2   \
matchid                                                           1   
gameid                                        ESPORTSTMNT03/1241318   
datacompleteness

Lets now isolate our league of interest

In [28]:
#isolate LCS
array = ['LCS']
LCS_data = game_data.loc[game_data['league'].isin(array)]
print(LCS_data.head())
LCS_data.info()

     matchid                 gameid datacompleteness  \
864       19  ESPORTSTMNT02/1270555         complete   
865       19  ESPORTSTMNT02/1270555         complete   
866       19  ESPORTSTMNT02/1270555         complete   
867       19  ESPORTSTMNT02/1270555         complete   
868       19  ESPORTSTMNT02/1270555         complete   

                                                   url league  \
864  https://matchhistory.na.leagueoflegends.com/en...    LCS   
865  https://matchhistory.na.leagueoflegends.com/en...    LCS   
866  https://matchhistory.na.leagueoflegends.com/en...    LCS   
867  https://matchhistory.na.leagueoflegends.com/en...    LCS   
868  https://matchhistory.na.leagueoflegends.com/en...    LCS   

                             year   split playoffs                 date game  \
864 1970-01-01 00:00:00.000002020  Spring        0  2020-01-25 21:37:53    1   
865 1970-01-01 00:00:00.000002020  Spring        0  2020-01-25 21:37:53    1   
866 1970-01-01 00:00:00.00000202

In [29]:
#check for null columns
null_columns=LCS_data.columns[LCS_data.isnull().any()]
LCS_data[null_columns].isnull().sum().sort_values(ascending=False)

dragons (type unknown)    2509
elementaldrakes           2350
opp_elementaldrakes       2350
infernals                 2350
mountains                 2350
clouds                    2350
oceans                    2350
elders                    2340
firstherald               2340
dragons                   2340
opp_dragons               2340
gspd                      2340
opp_elders                2340
heralds                   2340
opp_heralds               2340
firstbaron                2340
barons                    2340
opp_barons                2340
firsttower                2340
towers                    2340
opp_towers                2340
firstmidtower             2340
firsttothreetowers        2340
firstdragon               2340
firstbloodassist           468
firstbloodkill             468
champion                   468
total cs                   468
firstbloodvictim           468
damageshare                468
earnedgoldshare            468
player                     468
ban5    

We note that the features with 2340+ null entries are team statistics -- meaning there are entries for each team but not for the players, as teams get credited with those game accomplishments. This means when we isolate the team entries these should no longer show up as null.

In [30]:
#find the rows with null game ids
LCS_data[LCS_data["gameid"].isnull()]

Empty DataFrame
Columns: [matchid, gameid, datacompleteness, url, league, year, split, playoffs, date, game, patch, playerid, side, position, player, team, champion, ban1, ban2, ban3, ban4, ban5, gamelength, match_result, result, kills, deaths, assists, teamkills, teamdeaths, doublekills, triplekills, quadrakills, pentakills, firstblood, firstbloodkill, firstbloodassist, firstbloodvictim, team kpm, ckpm, firstdragon, dragons, opp_dragons, elementaldrakes, opp_elementaldrakes, infernals, mountains, clouds, oceans, dragons (type unknown), elders, opp_elders, firstherald, heralds, opp_heralds, firstbaron, barons, opp_barons, firsttower, towers, opp_towers, firstmidtower, firsttothreetowers, inhibitors, opp_inhibitors, damagetochampions, dpm, damageshare, wardsplaced, wpm, wardskilled, wcpm, controlwardsbought, visionscore, vspm, totalgold, earnedgold, earned gpm, earnedgoldshare, goldspent, gspd, total cs, minionkills, monsterkills, monsterkillsownjungle, monsterkillsenemyjungle, cspm, goldat10, xpat10, csat10, opp_goldat10, opp_xpat10, opp_csat10, golddiffat10, xpdiffat10, csdiffat10, goldat15, xpat15, csat15, opp_goldat15, ...]
Index: []

[0 rows x 105 columns]

We find that there are no missing game IDs in our LCS dataframe, which is good (and verified above as well)

In [31]:
LCS_data[LCS_data['player'].isnull()].head(10000)

matchid                 gameid datacompleteness  \
874         19  ESPORTSTMNT02/1270555         complete   
875         19  ESPORTSTMNT02/1270555         complete   
886         19  ESPORTSTMNT02/1270576         complete   
887         19  ESPORTSTMNT02/1270576         complete   
898         19  ESPORTSTMNT02/1270592         complete   
...        ...                    ...              ...   
62555     1248  ESPORTSTMNT03/1441723         complete   
62566     1248  ESPORTSTMNT03/1441725          partial   
62567     1248  ESPORTSTMNT03/1441725          partial   
62578     1248  ESPORTSTMNT03/1441735         complete   
62579     1248  ESPORTSTMNT03/1441735         complete   

                                                     url league  \
874    https://matchhistory.na.leagueoflegends.com/en...    LCS   
875    https://matchhistory.na.leagueoflegends.com/en...    LCS   
886    https://matchhistory.na.leagueoflegends.com/en...    LCS   
887    https://matchhistory.na.leagueoflegends.com/en...    LCS   
898    https://matchhistory.na.leagueoflegends.com/en...    LCS   
...                                                  ...    ...   
62555  http://matchhistory.na.leagueoflegends.com/en/...    LCS   
62566  http://matchhistory.na.leagueoflegends.com/en/...    LCS   
62567  http://matchhistory.na.leagueoflegends.com/en/...    LCS   
62578  http://matchhistory.na.leagueoflegends.com/en/...    LCS   
62579  http://matchhistory.na.leagueoflegends.com/en/...    LCS   

                               year   split playoffs                 date  \
874   1970-01-01 00:00:00.000002020  Spring        0  2020-01-25 21:37:53   
875   1970-01-01 00:00:00.000002020  Spring        0  2020-01-25 21:37:53   
886   1970-01-01 00:00:00.000002020  Spring        0  2020-01-25 22:32:55   
887   1970-01-01 00:00:00.000002020  Spring        0  2020-01-25 22:32:55   
898   1970-01-01 00:00:00.000002020  Spring        0  2020-01-25 23:39:30   
...                             ...     ...      ...                  ...   
62555 1970-01-01 00:00:00.000002020  Summer        1  2020-08-20 20:35:30   
62566 1970-01-01 00:00:00.000002020  Summer        1  2020-08-20 21:26:14   
62567 1970-01-01 00:00:00.000002020  Summer        1  2020-08-20 21:26:14   
62578 1970-01-01 00:00:00.000002020  Summer        1  2020-08-20 23:33:01   
62579 1970-01-01 00:00:00.000002020  Summer        1  2020-08-20 23:33:01   

      game  ...  csdiffat10 goldat15   xpat15 csat15 opp_goldat15 opp_xpat15  \
874      1  ...        -7.0  22949.0  28643.0  485.0      22995.0    27534.0   
875      1  ...         7.0  22995.0  27534.0  481.0      22949.0    28643.0   
886      1  ...        -3.0  23196.0  26241.0  486.0      24778.0    29394.0   
887      1  ...         3.0  24778.0  29394.0  522.0      23196.0    26241.0   
898      1  ...        -1.0  24058.0  26322.0  461.0      22600.0    26940.0   
...    ...  ...         ...      ...      ...    ...          ...        ...   
62555    2  ...       -37.0  25952.0  28599.0  453.0      25950.0    28193.0   
62566    3  ...        24.0  24457.0  29149.0  493.0      23168.0    28698.0   
62567    3  ...       -24.0  23168.0  28698.0  490.0      24457.0    29149.0   
62578    4  ...        12.0  24352.0  28436.0  462.0      23542.0    28120.0   
62579    4  ...       -12.0  23542.0  28120.0  460.0      24352.0    28436.0   

      opp_csat15 golddiffat15 xpdiffat15 csdiffat15  
874        481.0        -46.0     1109.0        4.0  
875        485.0         46.0    -1109.0       -4.0  
886        522.0      -1582.0    -3153.0      -36.0  
887        486.0       1582.0     3153.0       36.0  
898        461.0       1458.0     -618.0        0.0  
...          ...          ...        ...        ...  
62555      475.0          2.0      406.0      -22.0  
62566      490.0       1289.0      451.0        3.0  
62567      493.0      -1289.0     -451.0       -3.0  
62578      460.0        810.0      316.0        2.0  
62579      462.0       -8

These entries likely correspond to entries for the "team" position, for which there are null stats on the individual player features... so lets filter further to confirm

In [32]:
#get numerical statistics
LCS_data.describe().T

count         mean          std      min      25%      50%  \
matchid       2808.0   524.106838   415.181450    19.00   116.00   374.50   
patch         2808.0    10.085598     0.050805    10.01    10.04    10.06   
gamelength    2808.0  2047.807692   391.541845  1337.00  1779.00  1964.50   
match_result  2808.0     0.957265     0.202295     0.00     1.00     1.00   
result        2808.0     0.500000     0.500089     0.00     0.00     0.50   
...              ...          ...          ...      ...      ...      ...   
opp_xpat15    2808.0  9669.880342  8771.203916  2681.00  4862.25  6308.50   
opp_csat15    2808.0   169.306268   157.763604     0.00    89.00   126.00   
golddiffat15  2808.0     0.000000  1301.683935 -7782.00  -555.25     0.00   
xpdiffat15    2808.0     0.000000   988.693202 -5909.00  -506.00     0.00   
csdiffat15    2808.0     0.000000    22.274800  -114.00   -11.00     0.00   

                  75%       max  
matchid        914.00   1248.00  
patch           10.14     10.16  
gamelength    2286.00   3680.00  
match_result     1.00      1.00  
result           1.00      1.00  
...               ...       ...  
opp_xpat15    7710.50  33530.00  
opp_csat15     149.00    594.00  
golddiffat15   555.25   7782.00  
xpdiffat15     506.00   5909.00  
csdiffat15      11.00    114.00  

[85 rows x 8 columns]

In [33]:
#lets look for missing entries:
missing = pd.concat([LCS_data.isnull().sum(), 100 * LCS_data.isnull().mean()], axis=1)
missing.columns=['count', '%']
missing.sort_values(by='count', ascending=False)
missing.head()

count    %
matchid               0  0.0
gameid                0  0.0
datacompleteness      0  0.0
url                   0  0.0
league                0  0.0

In [34]:
#lets find the number of unique games
print(LCS_data['gameid'].nunique())
LCS_data['playerid'].dtype

234


CategoricalDtype(categories=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 100, 200], ordered=False)

234 unique games

In [35]:
#isolate team performances
team = LCS_data.position == 'team'
LCS_data_by_team = LCS_data[team]

In [36]:
#run the code above to confirm that the null entries were from team stats
LCS_data_by_team[LCS_data_by_team['player'].isnull()].head(10000)

matchid                 gameid datacompleteness  \
874         19  ESPORTSTMNT02/1270555         complete   
875         19  ESPORTSTMNT02/1270555         complete   
886         19  ESPORTSTMNT02/1270576         complete   
887         19  ESPORTSTMNT02/1270576         complete   
898         19  ESPORTSTMNT02/1270592         complete   
...        ...                    ...              ...   
62555     1248  ESPORTSTMNT03/1441723         complete   
62566     1248  ESPORTSTMNT03/1441725          partial   
62567     1248  ESPORTSTMNT03/1441725          partial   
62578     1248  ESPORTSTMNT03/1441735         complete   
62579     1248  ESPORTSTMNT03/1441735         complete   

                                                     url league  \
874    https://matchhistory.na.leagueoflegends.com/en...    LCS   
875    https://matchhistory.na.leagueoflegends.com/en...    LCS   
886    https://matchhistory.na.leagueoflegends.com/en...    LCS   
887    https://matchhistory.na.leagueoflegends.com/en...    LCS   
898    https://matchhistory.na.leagueoflegends.com/en...    LCS   
...                                                  ...    ...   
62555  http://matchhistory.na.leagueoflegends.com/en/...    LCS   
62566  http://matchhistory.na.leagueoflegends.com/en/...    LCS   
62567  http://matchhistory.na.leagueoflegends.com/en/...    LCS   
62578  http://matchhistory.na.leagueoflegends.com/en/...    LCS   
62579  http://matchhistory.na.leagueoflegends.com/en/...    LCS   

                               year   split playoffs                 date  \
874   1970-01-01 00:00:00.000002020  Spring        0  2020-01-25 21:37:53   
875   1970-01-01 00:00:00.000002020  Spring        0  2020-01-25 21:37:53   
886   1970-01-01 00:00:00.000002020  Spring        0  2020-01-25 22:32:55   
887   1970-01-01 00:00:00.000002020  Spring        0  2020-01-25 22:32:55   
898   1970-01-01 00:00:00.000002020  Spring        0  2020-01-25 23:39:30   
...                             ...     ...      ...                  ...   
62555 1970-01-01 00:00:00.000002020  Summer        1  2020-08-20 20:35:30   
62566 1970-01-01 00:00:00.000002020  Summer        1  2020-08-20 21:26:14   
62567 1970-01-01 00:00:00.000002020  Summer        1  2020-08-20 21:26:14   
62578 1970-01-01 00:00:00.000002020  Summer        1  2020-08-20 23:33:01   
62579 1970-01-01 00:00:00.000002020  Summer        1  2020-08-20 23:33:01   

      game  ...  csdiffat10 goldat15   xpat15 csat15 opp_goldat15 opp_xpat15  \
874      1  ...        -7.0  22949.0  28643.0  485.0      22995.0    27534.0   
875      1  ...         7.0  22995.0  27534.0  481.0      22949.0    28643.0   
886      1  ...        -3.0  23196.0  26241.0  486.0      24778.0    29394.0   
887      1  ...         3.0  24778.0  29394.0  522.0      23196.0    26241.0   
898      1  ...        -1.0  24058.0  26322.0  461.0      22600.0    26940.0   
...    ...  ...         ...      ...      ...    ...          ...        ...   
62555    2  ...       -37.0  25952.0  28599.0  453.0      25950.0    28193.0   
62566    3  ...        24.0  24457.0  29149.0  493.0      23168.0    28698.0   
62567    3  ...       -24.0  23168.0  28698.0  490.0      24457.0    29149.0   
62578    4  ...        12.0  24352.0  28436.0  462.0      23542.0    28120.0   
62579    4  ...       -12.0  23542.0  28120.0  460.0      24352.0    28436.0   

      opp_csat15 golddiffat15 xpdiffat15 csdiffat15  
874        481.0        -46.0     1109.0        4.0  
875        485.0         46.0    -1109.0       -4.0  
886        522.0      -1582.0    -3153.0      -36.0  
887        486.0       1582.0     3153.0       36.0  
898        461.0       1458.0     -618.0        0.0  
...          ...          ...        ...        ...  
62555      475.0          2.0      406.0      -22.0  
62566      490.0       1289.0      451.0        3.0  
62567      493.0      -1289.0     -451.0       -3.0  
62578      460.0        810.0      316.0        2.0  
62579      462.0       -8

In [37]:
LCS_data_by_team.head(1000)
LCS_data_by_team.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 468 entries, 874 to 62579
Columns: 105 entries, matchid to csdiffat15
dtypes: category(3), datetime64[ns](1), float64(67), int64(18), object(16)
memory usage: 378.7+ KB


In [38]:
#isolate stats for the first game of the first match in the dataframe
first_game = LCS_data_by_team.gameid == 'ESPORTSTMNT02/1270555'
LCS_data_first_game = LCS_data_by_team[first_game]
LCS_data_first_game.head(13)

matchid                 gameid datacompleteness  \
874       19  ESPORTSTMNT02/1270555         complete   
875       19  ESPORTSTMNT02/1270555         complete   

                                                   url league  \
874  https://matchhistory.na.leagueoflegends.com/en...    LCS   
875  https://matchhistory.na.leagueoflegends.com/en...    LCS   

                             year   split playoffs                 date game  \
874 1970-01-01 00:00:00.000002020  Spring        0  2020-01-25 21:37:53    1   
875 1970-01-01 00:00:00.000002020  Spring        0  2020-01-25 21:37:53    1   

     ...  csdiffat10 goldat15   xpat15 csat15 opp_goldat15 opp_xpat15  \
874  ...        -7.0  22949.0  28643.0  485.0      22995.0    27534.0   
875  ...         7.0  22995.0  27534.0  481.0      22949.0    28643.0   

    opp_csat15 golddiffat15 xpdiffat15 csdiffat15  
874      481.0        -46.0     1109.0        4.0  
875      485.0         46.0    -1109.0       -4.0  

[2 rows x 105 columns]

Note there are two entries now instead of 12, as we have filtered out the individual player performance rows

In [39]:
#select all numeric columns
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
newdf = LCS_data_first_game.select_dtypes(include=numerics)
all_stats = newdf.columns



In [40]:
#group totals by teamname
team_totals = LCS_data_first_game.groupby(by='team')[all_stats].sum().round(2)
print(team_totals.head())
team_totals.info()


             matchid  patch  gamelength  match_result  result  kills  deaths  \
team                                                                           
Cloud9            19  10.01        1474             1       1      9       3   
Team Liquid       19  10.01        1474             1       0      3       9   

             assists  teamkills  teamdeaths  ...  csdiffat10  goldat15  \
team                                         ...                         
Cloud9            18          9           3  ...        -7.0   22949.0   
Team Liquid        6          3           9  ...         7.0   22995.0   

              xpat15  csat15  opp_goldat15  opp_xpat15  opp_csat15  \
team                                                                 
Cloud9       28643.0   485.0       22995.0     27534.0       481.0   
Team Liquid  27534.0   481.0       22949.0     28643.0       485.0   

             golddiffat15  xpdiffat15  csdiffat15  
team                                             

In [59]:
#filter the game data by key stats
key_stats = ['result', 'match_result', 'gamelength', 'kills', 'deaths', 'assists', 'wardskilled', 'controlwardsbought', 'totalgold', 'earnedgold', 'goldspent', 'minionkills', 'monsterkills']
team_totals_key = LCS_data_by_team.groupby(by='team')[key_stats].sum().round(2)
print(team_totals_key.head(12))
print(team_totals_key.info())

                      result  match_result  gamelength  kills  deaths  \
team                                                                    
100 Thieves               20            47       98775    534     625   
Cloud9                    40            48       92464    775     430   
Counter Logic Gaming       8            35       76646    360     532   
Dignitas                  15            39       86579    390     464   
Evil Geniuses             29            55      114558    626     703   
FlyQuest                  38            63      132883    830     682   
Golden Guardians          21            42       89737    416     511   
Immortals                 12            36       80059    298     462   
Team Liquid               22            34       76267    385     295   
Team SoloMid              29            49      110406    617     532   

                      assists  wardskilled  controlwardsbought  totalgold  \
team                                          

Things left to do:
1) We need a new way of identifying matches
2) We need a way to count number of games each team participated in
3) We need a way to count number of matches each team participated in